
public class ExceptionsVideoExamples {

	public static void main(String[] args) {
		exceptionOne();
		
		exceptionTwo();
		System.out.println("In main");
		
	}
	
	/**
	 * first exception example
	 */
	public static void exceptionOne() {
		int a, b = 6;
		 
		 try {
			 a = b / 0;
		 } catch(ArithmeticException ae) {
			 a = b;
			 System.out.println("Arithmetic Exception: " + ae.getMessage());
		 }
	}
	
	/**
	 * second exception example
	 */
	public static void exceptionTwo() {
		System.out.println("In exceptionTwo");
		exceptionTwoStackOne();
	}
	
	public static void exceptionTwoStackOne() {
		int num = 45;
		System.out.println("In exceptionTwoStackOne");
	}

}
